# Generated by Django 4.1.1 on 2023-04-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_cartitem_cart_items_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qty',
            new_name='quantity',
        ),
    ]
