# Generated by Django 4.1.1 on 2023-03-31 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(default=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='last_modified',
            field=models.DateTimeField(default=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='title',
            field=models.CharField(default='Delivery', max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='address',
            field=models.CharField(default='Address', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='created_at',
            field=models.DateTimeField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='currency',
            field=models.CharField(default='Currency', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='settings',
            name='last_modified',
            field=models.DateTimeField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(default=True, upload_to='settings/images/'),
        ),
        migrations.AddField(
            model_name='settings',
            name='phone',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='title',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 31, 15, 50, 40, 223393)),
        ),
    ]
