# Generated by Django 4.1.1 on 2023-03-31 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delivery_active_delivery_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 31, 15, 54, 17, 588923)),
        ),
    ]
