# Generated by Django 4.1.1 on 2023-03-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='forget_pasword_token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
