# Generated by Django 4.1.1 on 2023-04-05 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authes', '0003_login_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
