# Generated by Django 4.1.1 on 2023-04-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authes', '0005_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
