# Generated by Django 4.1.1 on 2023-04-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Premium', 'prememium'), ('Free', 'free')], default='Free', max_length=30),
        ),
    ]
