# Generated by Django 4.1.1 on 2023-04-08 15:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0003_remove_subscription_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSettingz',
            new_name='UserSettings',
        ),
    ]
